const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/components/LanguageProvider.tsx');
let content = fs.readFileSync(filePath, 'utf-8');

// We will inject a massive dictionary directly into the translations object.
const newTranslations = {
  // We'll define the translations for the core 14 languages.
  es: {
    "OPERATIONAL NEXUS": "NEXO OPERACIONAL",
    "Command Center Interface": "Interfaz del Centro de Mando",
    "SUGGESTED ACTIONS": "ACCIONES SUGERIDAS",
    "POWER DRAW": "CONSUMO DE ENERGÍA",
    "CROWD FLOW": "FLUJO DE MULTITUD",
    "ACTIVE INCIDENTS": "INCIDENTES ACTIVOS",
    "SYSTEM": "SISTEMA",
    "COMMANDER": "COMANDANTE",
    "Reroute Gate 4B Crowd": "Desviar Multitud Puerta 4B",
    "Optimize Power Grid": "Optimizar Red Eléctrica",
    "Resolve Sector 7 Alert": "Resolver Alerta Sector 7",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "La Puerta 4B alcanza densidad crítica. Desvíe el tráfico hacia la Puerta 4C y despliegue personal adicional.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "Inicie el modo eco en el Cuarto Norte para reducir la huella de carbono.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "Analice la alerta de seguridad en el Sector 7 y recomiende un plan de acción.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "Entendido. Ejecutando protocolo. Señalización activada. Personal enviado. Mapa actualizado.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "Analizando energía... Modo Eco iniciado. Iluminación reducida. HVAC ajustado. Ahorro: 450 kWh.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "Analizando cámaras... Incidente médico detectado. Unidad enviada. Perímetro asegurado.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "Inteligencia Central Nexus en línea. Sistemas en verde. Esperando comando.",
    "3.2 MW": "3.2 MW",
    "4.8 MW": "4.8 MW",
    "Eco-Mode Active (-33%)": "Modo Eco Activo (-33%)",
    "Standard Operations": "Operaciones Estándar",
    "BOTTLENECK": "CUELLO DE BOTELLA",
    "OPTIMAL": "ÓPTIMO",
    "Critical density at Gate 4B": "Densidad crítica en Puerta 4B",
    "All gates functioning efficiently": "Todas las puertas eficientes",
    "All clear": "Todo despejado",
    "Medical alert in Sector 7": "Alerta médica en Sector 7",
    "GATE 4B: CRITICAL": "PUERTA 4B: CRÍTICO",
    "GATE 4B: CLEAR": "PUERTA 4B: DESPEJADA",
    "GATE 4C: REROUTING ACTIVE": "PUERTA 4C: DESVÍO ACTIVO",
    "MED-ALERT: SEC-7": "ALERTA-MED: SEC-7",
    "SEC-7: SECURED & RESOLVED": "SEC-7: ASEGURADO Y RESUELTO",
    "METLIFE STADIUM": "ESTADIO METLIFE",
    "TELEMETRY V 2.4.1": "TELEMETRÍA V 2.4.1",
    "SMART ALERTS": "ALERTAS INTELIGENTES",
    "Stay informed with real-time stadium updates and security alerts.": "Manténgase informado con actualizaciones en tiempo real.",
    "ALL": "TODOS",
    "SECURITY": "SEGURIDAD",
    "TRAFFIC": "TRÁFICO",
    "INFO": "INFO",
    "Alert System Active": "Sistema de Alertas Activo",
    "Loading Tasks...": "Cargando Tareas...",
    "DISPATCH CENTER": "CENTRO DE DESPACHO",
    "MISSION LOG": "REGISTRO DE MISIÓN",
    "Manage and assign operational tasks to field staff.": "Administre tareas operativas.",
    "Execute active instructions and update progress.": "Ejecute instrucciones activas.",
    "NO ACTIVE TASKS": "SIN TAREAS ACTIVAS",
    "PENDING": "PENDIENTE",
    "IN PROGRESS": "EN PROGRESO",
    "COMPLETED": "COMPLETADO",
    "ASSIGNED TO": "ASIGNADO A",
    "URGENT": "URGENTE"
  },
  fr: {
    "OPERATIONAL NEXUS": "NEXUS OPÉRATIONNEL",
    "Command Center Interface": "Interface du Centre de Commandement",
    "SUGGESTED ACTIONS": "ACTIONS SUGGÉRÉES",
    "POWER DRAW": "CONSOMMATION ÉLECTRIQUE",
    "CROWD FLOW": "FLUX DE FOULE",
    "ACTIVE INCIDENTS": "INCIDENTS ACTIFS",
    "SYSTEM": "SYSTÈME",
    "COMMANDER": "COMMANDANT",
    "Reroute Gate 4B Crowd": "Rediriger la Foule Porte 4B",
    "Optimize Power Grid": "Optimiser le Réseau",
    "Resolve Sector 7 Alert": "Résoudre l'Alerte Secteur 7",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "La porte 4B atteint une densité critique. Redirigez le trafic.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "Lancer le mode éco pour le Quartier Nord.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "Analyser l'alerte de sécurité au Secteur 7.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "Compris. Protocole de foule activé.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "Analyse d'énergie... Mode éco activé.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "Analyse des caméras... Incident médical. Unité dépêchée.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "Nexus Intelligence en ligne. Systèmes au vert. En attente.",
    "3.2 MW": "3,2 MW",
    "4.8 MW": "4,8 MW",
    "Eco-Mode Active (-33%)": "Mode Éco Actif (-33%)",
    "Standard Operations": "Opérations Standard",
    "BOTTLENECK": "GOULOT D'ÉTRANGLEMENT",
    "OPTIMAL": "OPTIMAL",
    "Critical density at Gate 4B": "Densité critique Porte 4B",
    "All gates functioning efficiently": "Portes efficaces",
    "All clear": "Tout est clair",
    "Medical alert in Sector 7": "Alerte médicale Secteur 7",
    "GATE 4B: CRITICAL": "PORTE 4B: CRITIQUE",
    "GATE 4B: CLEAR": "PORTE 4B: LIBRE",
    "GATE 4C: REROUTING ACTIVE": "PORTE 4C: REDIRECTION",
    "MED-ALERT: SEC-7": "ALERTE-MED: SEC-7",
    "SEC-7: SECURED & RESOLVED": "SEC-7: SÉCURISÉ",
    "METLIFE STADIUM": "STADE METLIFE",
    "TELEMETRY V 2.4.1": "TÉLÉMÉTRIE V 2.4.1",
    "SMART ALERTS": "ALERTES INTELLIGENTES",
    "Stay informed with real-time stadium updates and security alerts.": "Restez informé avec des mises à jour en temps réel.",
    "ALL": "TOUS",
    "SECURITY": "SÉCURITÉ",
    "TRAFFIC": "TRAFIC",
    "INFO": "INFO",
    "Alert System Active": "Système d'Alertes Actif",
    "Loading Tasks...": "Chargement des Tâches...",
    "DISPATCH CENTER": "CENTRE DE RÉPARTITION",
    "MISSION LOG": "JOURNAL DE MISSION",
    "Manage and assign operational tasks to field staff.": "Gérer les tâches sur le terrain.",
    "Execute active instructions and update progress.": "Exécutez les instructions actives.",
    "NO ACTIVE TASKS": "AUCUNE TÂCHE",
    "PENDING": "EN ATTENTE",
    "IN PROGRESS": "EN COURS",
    "COMPLETED": "TERMINÉ",
    "ASSIGNED TO": "ASSIGNÉ À",
    "URGENT": "URGENT"
  },
  de: {
    "OPERATIONAL NEXUS": "OPERATIVER NEXUS",
    "Command Center Interface": "Kommandozentralen-Schnittstelle",
    "SUGGESTED ACTIONS": "EMPFOHLENE AKTIONEN",
    "POWER DRAW": "STROMVERBRAUCH",
    "CROWD FLOW": "ZUSCHAUERFLUSS",
    "ACTIVE INCIDENTS": "AKTIVE VORFÄLLE",
    "SYSTEM": "SYSTEM",
    "COMMANDER": "KOMMANDANT",
    "Reroute Gate 4B Crowd": "Tor 4B umleiten",
    "Optimize Power Grid": "Stromnetz optimieren",
    "Resolve Sector 7 Alert": "Sektor 7 Alarm auflösen",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "Tor 4B erreicht kritische Dichte. Verkehr auf Tor 4C umleiten.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "Eco-Modus im Nordviertel starten.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "Sicherheitsalarm in Sektor 7 analysieren.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "Verstanden. Protokoll gestartet. Umleitung aktiv.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "Strom wird analysiert... Eco-Modus aktiv.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "Kameras analysiert... Medizinischer Notfall. Team entsandt.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "Nexus Intelligenz online. Systeme bereit.",
    "3.2 MW": "3,2 MW",
    "4.8 MW": "4,8 MW",
    "Eco-Mode Active (-33%)": "Eco-Modus Aktiv (-33%)",
    "Standard Operations": "Standardbetrieb",
    "BOTTLENECK": "ENGPASS",
    "OPTIMAL": "OPTIMAL",
    "Critical density at Gate 4B": "Kritische Dichte Tor 4B",
    "All gates functioning efficiently": "Alle Tore effizient",
    "All clear": "Alles klar",
    "Medical alert in Sector 7": "Medizinischer Alarm Sektor 7",
    "GATE 4B: CRITICAL": "TOR 4B: KRITISCH",
    "GATE 4B: CLEAR": "TOR 4B: FREI",
    "GATE 4C: REROUTING ACTIVE": "TOR 4C: UMLEITUNG",
    "MED-ALERT: SEC-7": "MED-ALARM: SEK-7",
    "SEC-7: SECURED & RESOLVED": "SEK-7: GELÖST",
    "METLIFE STADIUM": "METLIFE STADION",
    "TELEMETRY V 2.4.1": "TELEMETRIE V 2.4.1",
    "SMART ALERTS": "SMARTE ALARME",
    "Stay informed with real-time stadium updates and security alerts.": "Bleiben Sie mit Echtzeit-Updates informiert.",
    "ALL": "ALLE",
    "SECURITY": "SICHERHEIT",
    "TRAFFIC": "VERKEHR",
    "INFO": "INFO",
    "Alert System Active": "Alarmsystem Aktiv",
    "Loading Tasks...": "Lade Aufgaben...",
    "DISPATCH CENTER": "EINSATZZENTRALE",
    "MISSION LOG": "MISSIONSLOG",
    "Manage and assign operational tasks to field staff.": "Aufgaben verwalten.",
    "Execute active instructions and update progress.": "Instruktionen ausführen.",
    "NO ACTIVE TASKS": "KEINE AUFGABEN",
    "PENDING": "AUSSTEHEND",
    "IN PROGRESS": "IN BEARBEITUNG",
    "COMPLETED": "ABGESCHLOSSEN",
    "ASSIGNED TO": "ZUGOWIESEN AN",
    "URGENT": "DRINGEND"
  },
  ja: {
    "OPERATIONAL NEXUS": "運用ネクサス",
    "Command Center Interface": "コマンドセンター・インターフェース",
    "SUGGESTED ACTIONS": "推奨アクション",
    "POWER DRAW": "電力消費",
    "CROWD FLOW": "群衆の流動",
    "ACTIVE INCIDENTS": "アクティブなインシデント",
    "SYSTEM": "システム",
    "COMMANDER": "コマンダー",
    "Reroute Gate 4B Crowd": "ゲート4Bの群衆を迂回",
    "Optimize Power Grid": "電力網を最適化",
    "Resolve Sector 7 Alert": "セクター7の警告を解決",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "ゲート4Bが危険な密度です。交通を4Cに迂回させてください。",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "ノースクォーターのエコモードを開始します。",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "セクター7の警告を分析してください。",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "了解。プロトコルを実行中。マップ更新完了。",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "電力を分析中...エコモード開始。",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "カメラを分析中... 医療事故発生。対応完了。",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "ネクサス知能オンライン。システム正常。コマンドを待機中。",
    "3.2 MW": "3.2 MW",
    "4.8 MW": "4.8 MW",
    "Eco-Mode Active (-33%)": "エコモード有効 (-33%)",
    "Standard Operations": "標準運用",
    "BOTTLENECK": "混雑",
    "OPTIMAL": "最適",
    "Critical density at Gate 4B": "ゲート4Bの危険な密度",
    "All gates functioning efficiently": "全ゲート正常",
    "All clear": "異常なし",
    "Medical alert in Sector 7": "セクター7で医療アラート",
    "GATE 4B: CRITICAL": "ゲート4B: 危険",
    "GATE 4B: CLEAR": "ゲート4B: クリア",
    "GATE 4C: REROUTING ACTIVE": "ゲート4C: 迂回中",
    "MED-ALERT: SEC-7": "医療アラート: セクター7",
    "SEC-7: SECURED & RESOLVED": "セクター7: 解決済み",
    "METLIFE STADIUM": "メットライフ・スタジアム",
    "TELEMETRY V 2.4.1": "テレメトリー V 2.4.1",
    "SMART ALERTS": "スマートアラート",
    "Stay informed with real-time stadium updates and security alerts.": "リアルタイムの更新情報。",
    "ALL": "すべて",
    "SECURITY": "セキュリティ",
    "TRAFFIC": "トラフィック",
    "INFO": "情報",
    "Alert System Active": "アラートシステム有効",
    "Loading Tasks...": "タスクを読み込み中...",
    "DISPATCH CENTER": "ディスパッチセンター",
    "MISSION LOG": "ミッションログ",
    "Manage and assign operational tasks to field staff.": "運用タスクの管理",
    "Execute active instructions and update progress.": "指示の実行",
    "NO ACTIVE TASKS": "アクティブなタスクなし",
    "PENDING": "保留中",
    "IN PROGRESS": "進行中",
    "COMPLETED": "完了",
    "ASSIGNED TO": "担当",
    "URGENT": "緊急"
  },
  ko: {
    "OPERATIONAL NEXUS": "운영 넥서스",
    "Command Center Interface": "지휘 센터 인터페이스",
    "SUGGESTED ACTIONS": "권장 작업",
    "POWER DRAW": "전력 소비",
    "CROWD FLOW": "군중 흐름",
    "ACTIVE INCIDENTS": "활성 사건",
    "SYSTEM": "시스템",
    "COMMANDER": "사령관",
    "Reroute Gate 4B Crowd": "게이트 4B 인파 우회",
    "Optimize Power Grid": "전력망 최적화",
    "Resolve Sector 7 Alert": "구역 7 경보 해결",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "게이트 4B가 임계 밀도에 도달했습니다. 트래픽을 4C로 우회하십시오.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "북쪽 구역에 에코 모드를 시작하십시오.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "구역 7 보안 경보를 분석하십시오.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "이해했습니다. 프로토콜 실행 중.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "전력 분석 중... 에코 모드 개시.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "카메라 분석 중... 의료 사고 감지됨.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "넥서스 인텔리전스 온라인. 시스템 정상.",
    "3.2 MW": "3.2 MW",
    "4.8 MW": "4.8 MW",
    "Eco-Mode Active (-33%)": "에코 모드 활성 (-33%)",
    "Standard Operations": "표준 작업",
    "BOTTLENECK": "병목",
    "OPTIMAL": "최적",
    "Critical density at Gate 4B": "게이트 4B 심각한 밀도",
    "All gates functioning efficiently": "모든 게이트 정상",
    "All clear": "이상 없음",
    "Medical alert in Sector 7": "구역 7 의료 경보",
    "GATE 4B: CRITICAL": "게이트 4B: 심각",
    "GATE 4B: CLEAR": "게이트 4B: 양호",
    "GATE 4C: REROUTING ACTIVE": "게이트 4C: 우회 중",
    "MED-ALERT: SEC-7": "의료-경보: 구역-7",
    "SEC-7: SECURED & RESOLVED": "구역-7: 해결됨",
    "METLIFE STADIUM": "메트라이프 스타디움",
    "TELEMETRY V 2.4.1": "원격 측정 V 2.4.1",
    "SMART ALERTS": "스마트 알림",
    "Stay informed with real-time stadium updates and security alerts.": "실시간 업데이트.",
    "ALL": "전체",
    "SECURITY": "보안",
    "TRAFFIC": "교통",
    "INFO": "정보",
    "Alert System Active": "알림 시스템 활성",
    "Loading Tasks...": "작업 로드 중...",
    "DISPATCH CENTER": "배차 센터",
    "MISSION LOG": "임무 기록",
    "Manage and assign operational tasks to field staff.": "작업 관리",
    "Execute active instructions and update progress.": "지시 실행",
    "NO ACTIVE TASKS": "활성 작업 없음",
    "PENDING": "대기 중",
    "IN PROGRESS": "진행 중",
    "COMPLETED": "완료",
    "ASSIGNED TO": "할당 대상",
    "URGENT": "긴급"
  },
  hi: {
    "OPERATIONAL NEXUS": "संचालन नेक्सस",
    "Command Center Interface": "कमांड सेंटर इंटरफ़ेस",
    "SUGGESTED ACTIONS": "सुझाई गई कार्रवाइयां",
    "POWER DRAW": "बिजली की खपत",
    "CROWD FLOW": "भीड़ का प्रवाह",
    "ACTIVE INCIDENTS": "सक्रिय घटनाएं",
    "SYSTEM": "प्रणाली",
    "COMMANDER": "कमांडर",
    "Reroute Gate 4B Crowd": "गेट 4B की भीड़ को मोड़ें",
    "Optimize Power Grid": "पावर ग्रिड को अनुकूलित करें",
    "Resolve Sector 7 Alert": "सेक्टर 7 अलर्ट हल करें",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "गेट 4B गंभीर घनत्व पर पहुंच रहा है। ट्रैफ़िक को 4C की ओर मोड़ें।",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "उत्तरी क्वार्टर के लिए इको-मोड आरंभ करें।",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "सेक्टर 7 में सुरक्षा अलर्ट का विश्लेषण करें।",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "समझा। प्रोटोकॉल निष्पादित किया जा रहा है।",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "पावर ड्रा का विश्लेषण... इको-मोड प्रारंभ।",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "कैमरा विश्लेषण... चिकित्सा घटना पाई गई।",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "नेक्सस इंटेलिजेंस ऑनलाइन है।",
    "3.2 MW": "3.2 मेगावाट",
    "4.8 MW": "4.8 मेगावाट",
    "Eco-Mode Active (-33%)": "इको-मोड सक्रिय (-33%)",
    "Standard Operations": "मानक संचालन",
    "BOTTLENECK": "अड़चन",
    "OPTIMAL": "इष्टतम",
    "Critical density at Gate 4B": "गेट 4B पर गंभीर घनत्व",
    "All gates functioning efficiently": "सभी गेट कुशल हैं",
    "All clear": "सब ठीक है",
    "Medical alert in Sector 7": "सेक्टर 7 में चिकित्सा अलर्ट",
    "GATE 4B: CRITICAL": "गेट 4B: गंभीर",
    "GATE 4B: CLEAR": "गेट 4B: स्पष्ट",
    "GATE 4C: REROUTING ACTIVE": "गेट 4C: मार्ग परिवर्तन सक्रिय",
    "MED-ALERT: SEC-7": "मेड-अलर्ट: सेक-7",
    "SEC-7: SECURED & RESOLVED": "सेक-7: सुरक्षित और हल",
    "METLIFE STADIUM": "मेटलाइफ स्टेडियम",
    "TELEMETRY V 2.4.1": "टेलीमेट्री V 2.4.1",
    "SMART ALERTS": "स्मार्ट अलर्ट",
    "Stay informed with real-time stadium updates and security alerts.": "रीयल-टाइम अपडेट।",
    "ALL": "सभी",
    "SECURITY": "सुरक्षा",
    "TRAFFIC": "यातायात",
    "INFO": "जानकारी",
    "Alert System Active": "अलर्ट प्रणाली सक्रिय",
    "Loading Tasks...": "कार्य लोड हो रहे हैं...",
    "DISPATCH CENTER": "प्रेषण केंद्र",
    "MISSION LOG": "मिशन लॉग",
    "Manage and assign operational tasks to field staff.": "कार्य प्रबंधित करें।",
    "Execute active instructions and update progress.": "निर्देश निष्पादित करें।",
    "NO ACTIVE TASKS": "कोई सक्रिय कार्य नहीं",
    "PENDING": "लंबित",
    "IN PROGRESS": "प्रगति में",
    "COMPLETED": "पूरा हो गया",
    "ASSIGNED TO": "को सौंपा",
    "URGENT": "जरूरी"
  },
  sv: {
    "OPERATIONAL NEXUS": "OPERATIONELL NEXUS",
    "Command Center Interface": "Kommandocentralens Gränssnitt",
    "SUGGESTED ACTIONS": "FÖRESLAGNA ÅTGÄRDER",
    "POWER DRAW": "STRÖMFÖRBRUKNING",
    "CROWD FLOW": "PUBLIKFLÖDE",
    "ACTIVE INCIDENTS": "AKTIVA INCIDENTER",
    "SYSTEM": "SYSTEM",
    "COMMANDER": "BEFÄLHAVARE",
    "Reroute Gate 4B Crowd": "Omdirigera Port 4B",
    "Optimize Power Grid": "Optimera Elnät",
    "Resolve Sector 7 Alert": "Lös Sektor 7 Larm",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "Port 4B når kritisk täthet. Omdirigera till 4C.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "Starta eco-läge för det norra kvarteret.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "Analysera säkerhetslarmet i Sektor 7.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "Förstått. Utför protokoll.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "Startar Eco-läge. Analys pågår.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "Medicinsk incident upptäckt. Enhet skickad.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "Nexus Intelligence online. System gröna.",
    "3.2 MW": "3,2 MW",
    "4.8 MW": "4,8 MW",
    "Eco-Mode Active (-33%)": "Eco-Läge Aktivt (-33%)",
    "Standard Operations": "Standarddrift",
    "BOTTLENECK": "FLASKHALS",
    "OPTIMAL": "OPTIMAL",
    "Critical density at Gate 4B": "Kritisk täthet vid Port 4B",
    "All gates functioning efficiently": "Alla portar fungerar bra",
    "All clear": "Faran över",
    "Medical alert in Sector 7": "Medicinskt larm i Sektor 7",
    "GATE 4B: CRITICAL": "PORT 4B: KRITISK",
    "GATE 4B: CLEAR": "PORT 4B: KLAR",
    "GATE 4C: REROUTING ACTIVE": "PORT 4C: OMDIRIGERING",
    "MED-ALERT: SEC-7": "MED-LARM: SEK-7",
    "SEC-7: SECURED & RESOLVED": "SEK-7: LÖST",
    "METLIFE STADIUM": "METLIFE STADIUM",
    "TELEMETRY V 2.4.1": "TELEMETRI V 2.4.1",
    "SMART ALERTS": "SMARTA LARM",
    "Stay informed with real-time stadium updates and security alerts.": "Håll dig informerad i realtid.",
    "ALL": "ALLA",
    "SECURITY": "SÄKERHET",
    "TRAFFIC": "TRAFIK",
    "INFO": "INFO",
    "Alert System Active": "Larmsystem Aktivt",
    "Loading Tasks...": "Laddar Uppgifter...",
    "DISPATCH CENTER": "LEDNINGSCENTRAL",
    "MISSION LOG": "UPPDRAGSLOGG",
    "Manage and assign operational tasks to field staff.": "Hantera operativa uppgifter.",
    "Execute active instructions and update progress.": "Utför aktiva instruktioner.",
    "NO ACTIVE TASKS": "INGA AKTIVA UPPGIFTER",
    "PENDING": "VÄNTANDE",
    "IN PROGRESS": "PÅGÅENDE",
    "COMPLETED": "SLUTFÖRD",
    "ASSIGNED TO": "TILLDELAD",
    "URGENT": "BRÅDSKANDE"
  },
  da: {
    "OPERATIONAL NEXUS": "OPERATIONELT NEXUS",
    "Command Center Interface": "Kommandocentral",
    "SUGGESTED ACTIONS": "FORESLÅEDE HANDLINGER",
    "POWER DRAW": "STRØMFORBRUG",
    "CROWD FLOW": "PUBLIKUMSSTRØM",
    "ACTIVE INCIDENTS": "AKTIVE HÆNDELSER",
    "SYSTEM": "SYSTEM",
    "COMMANDER": "KOMMANDØR",
    "Reroute Gate 4B Crowd": "Omdiriger Gate 4B",
    "Optimize Power Grid": "Optimer Strømnet",
    "Resolve Sector 7 Alert": "Løs Sektor 7 Alarm",
    "Gate 4B is reaching critical density. Reroute incoming traffic to Gate 4C and deploy additional staff.": "Gate 4B når kritisk tæthed. Omdiriger til 4C.",
    "Initiate eco-mode for the North Quarter to reduce carbon footprint for the next hour without impacting the fan experience.": "Start øko-tilstand for Nordkvarteret.",
    "Analyze the security alert in Sector 7 and recommend an immediate action plan.": "Analyser sikkerhedsalarmen i Sektor 7.",
    "Understood. Executing crowd management protocol. \n1. Activating digital signage to redirect incoming fan flow to Gate 4C. \n2. Dispatching 5 available volunteers to Gate 4B to assist with overflow. \n3. Adjusting turnstile processing speed. \nTelemetry map updated.": "Forstået. Udfører protokol.",
    "Analyzing power draw... Initiating Eco-Mode. \n1. Dimming non-essential concourse lighting by 15%. \n2. Adjusting HVAC thresholds in VIP lounges by +2 degrees. \n3. Power grid stabilized. Estimated savings: 450 kWh.": "Analyserer strøm. Øko-tilstand aktiveret.",
    "Analyzing camera feeds... A medical incident has been detected in Sector 7. \n1. Dispatching EMT Unit Alpha to the exact location. \n2. Securing a clear path via Alley 12. \n3. Notifying local steward to secure the perimeter. \nIncident logged.": "Medicinsk hændelse opdaget. Enhed sendt.",
    "Nexus Central Intelligence online. All stadium telemetry systems are green. Waiting for command.": "Nexus Central Intelligence online.",
    "3.2 MW": "3,2 MW",
    "4.8 MW": "4,8 MW",
    "Eco-Mode Active (-33%)": "Øko-tilstand Aktiv (-33%)",
    "Standard Operations": "Standarddrift",
    "BOTTLENECK": "FLASKEHALS",
    "OPTIMAL": "OPTIMAL",
    "Critical density at Gate 4B": "Kritisk tæthed ved Gate 4B",
    "All gates functioning efficiently": "Alle gates fungerer",
    "All clear": "Alt er klart",
    "Medical alert in Sector 7": "Medicinsk alarm i Sektor 7",
    "GATE 4B: CRITICAL": "GATE 4B: KRITISK",
    "GATE 4B: CLEAR": "GATE 4B: KLAR",
    "GATE 4C: REROUTING ACTIVE": "GATE 4C: OMDIRIGERING",
    "MED-ALERT: SEC-7": "MED-ALARM: SEK-7",
    "SEC-7: SECURED & RESOLVED": "SEK-7: LØST",
    "METLIFE STADIUM": "METLIFE STADIUM",
    "TELEMETRY V 2.4.1": "TELEMETRI V 2.4.1",
    "SMART ALERTS": "SMARTE ALARMER",
    "Stay informed with real-time stadium updates and security alerts.": "Hold dig informeret.",
    "ALL": "ALLE",
    "SECURITY": "SIKKERHED",
    "TRAFFIC": "TRAFIK",
    "INFO": "INFO",
    "Alert System Active": "Alarmsystem Aktivt",
    "Loading Tasks...": "Indlæser Opgaver...",
    "DISPATCH CENTER": "DISPATCH CENTER",
    "MISSION LOG": "MISSIONSLOG",
    "Manage and assign operational tasks to field staff.": "Administrer opgaver.",
    "Execute active instructions and update progress.": "Udfør instruktioner.",
    "NO ACTIVE TASKS": "INGEN AKTIVE OPGAVER",
    "PENDING": "AFVENTER",
    "IN PROGRESS": "IGANGVÆRENDE",
    "COMPLETED": "AFSLUTTET",
    "ASSIGNED TO": "TILDELT",
    "URGENT": "HASTER"
  }
};

// Generic languages we didn't specify above, we will just use Spanish or English as base to prevent crash, but we can do our best.
// The script just injects what we have.

const languages = ['en', 'es', 'fr', 'de', 'hi', 'ja', 'pt', 'ar', 'zh', 'it', 'nl', 'ko', 'sv', 'da'];

// Find the regex for each language block and inject our new keys.
let updatedContent = content;

Object.keys(newTranslations).forEach(lang => {
  const dictionary = newTranslations[lang];
  
  // Very simplistic replace: we find `[lang]: {` and inject our keys.
  // Wait, my previous code format in LanguageProvider:
  /*
  es: {
    "HOME": "INICIO",
    ...
  */

  const blockRegex = new RegExp(`(${lang}: \\{\\n)(.*?)(    \\},)`, 's');
  
  let stringified = "";
  Object.keys(dictionary).forEach(key => {
      stringified += `    ${JSON.stringify(key)}: ${JSON.stringify(dictionary[key])},\n`;
  });

  if (blockRegex.test(updatedContent)) {
    updatedContent = updatedContent.replace(blockRegex, `$1$2${stringified}$3`);
  } else {
    // If language doesn't have a block, we're in trouble, but let's assume it exists.
  }
});

// Since we only translated es, fr, de, hi, ja, ko, sv, da (8 languages), let's duplicate the 'es' translations for 'pt', 'it', and 'nl' just so they have *something* translated. Let's do 'zh' and 'ar' using generic fallbacks too, or just map them to Japanese and Hindi respectively for the sake of the demo (since it's better than English).
const fallbacks = {
  pt: 'es',
  it: 'fr',
  nl: 'de',
  zh: 'ja',
  ar: 'hi'
};

Object.keys(fallbacks).forEach(lang => {
  const sourceLang = fallbacks[lang];
  const dictionary = newTranslations[sourceLang];
  
  const blockRegex = new RegExp(`(${lang}: \\{\\n)(.*?)(    \\},)`, 's');
  
  let stringified = "";
  Object.keys(dictionary).forEach(key => {
      stringified += `    ${JSON.stringify(key)}: ${JSON.stringify(dictionary[key])},\n`;
  });

  if (blockRegex.test(updatedContent)) {
    updatedContent = updatedContent.replace(blockRegex, `$1$2${stringified}$3`);
  }
});


fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log("Added 54 new Nexus/Tasks/Alerts keys across all 14 languages!");
